name: ci
run-name: ci run by ${{ github.actor }}

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: weather-site-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
      AWS_DEFAULT_ACCOUNT_ID: '123456789012'
      AWS_DEFAULT_REGION: us-west-2
    permissions:
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@v7

      - name: setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: '.nvmrc'
          cache: npm
          check-latest: true

      - name: install dependencies
        run: npm ci

      - name: build
        run: npm run build

      - name: run oxfmt format check
        run: npm run format:ci

      - name: run oxlint check
        run: npm run lint:ci

      - name: test
        run: npm test

      - name: cdk synth non custom domain stack
        run: npm run synth:quiet -- --no-lookups
        env:
          ALERT_EMAIL: test@test.com
          LOCATION_NAME: Pittsburgh, Pennsylvania
          OPEN_WEATHER_URL: https://openweathermap.org/city/5206379
          SCHEDULES: 'rate(60 minutes)'
          STACK_PREFIX: pitt-rain
          WEATHER_LOCATION_LAT: 40.4406
          WEATHER_LOCATION_LON: -79.9959
          WEATHER_TYPE: rain

      - name: cdk synth custom domain stack
        run: npm run synth:quiet -- --no-lookups
        env:
          LOCATION_NAME: Pittsburgh, Pennsylvania
          OPEN_WEATHER_URL: https://openweathermap.org/city/5206379
          SCHEDULES: 'rate(60 minutes)'
          STACK_PREFIX: pitt-rain
          DOMAIN_NAME: pitt-rain-site.com
          WEATHER_LOCATION_LAT: 40.4406
          WEATHER_LOCATION_LON: -79.9959
          WEATHER_TYPE: rain
